/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Conexion.ConexionMySql;

/**
 *
 * @author javier
 */
public class AccesoBbdd extends javax.swing.JFrame {

    public ConexionMySql conexion ;
    public Boolean acceso = false;
    
    /**
     * Creates new form AccesoBbdd
     */
    public AccesoBbdd() {
        initComponents();
        // centrar el formulario en la ventan
        this.setLocationRelativeTo(null);
        lblDisponibles.setVisible(false);
        lblNombreBbdd.setVisible(false);
        txtBaseDatos.setVisible(false);
        cmbBbdd.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcceso = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDisponibles = new javax.swing.JLabel();
        txtBaseDatos = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        cmbBbdd = new javax.swing.JComboBox<>();
        lblNombreBbdd = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAcceso.setBackground(new java.awt.Color(0, 0, 204));
        btnAcceso.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAcceso.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceso.setLabel("ACCEDER");
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, -1));

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jLabelIcono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelIconoMousePressed(evt);
            }
        });
        getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblDisponibles.setBackground(new java.awt.Color(0, 0, 153));
        lblDisponibles.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        lblDisponibles.setText("BBDD Disponibles");
        getContentPane().add(lblDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtBaseDatos.setBackground(new java.awt.Color(0, 0, 153));
        txtBaseDatos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtBaseDatos.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtBaseDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 160, -1));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 153));
        txtUsuario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, -1));

        txtContraseña.setBackground(new java.awt.Color(0, 0, 153));
        txtContraseña.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setText("jPasswordField1");
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseEntered(evt);
            }
        });
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 160, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 204));
        btnSalir.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        cmbBbdd.setBackground(new java.awt.Color(0, 0, 153));
        cmbBbdd.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cmbBbdd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBbddItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbBbdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, -1));

        lblNombreBbdd.setBackground(new java.awt.Color(0, 0, 153));
        lblNombreBbdd.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblNombreBbdd.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreBbdd.setText("Nombre BBDD ");
        getContentPane().add(lblNombreBbdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/azul.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 402, 433));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed
                    
        // si acceso es false con el usuario y contraseña busca las bases de datos
        if (acceso!=true) 
        {
            String cadena ="";
            if (txtUsuario.getText() != null && txtContraseña.getPassword() != null)
            {
                conexion = new ConexionMySql( txtUsuario.getText() , 
                        String.valueOf( txtContraseña.getPassword() ) );
                
                // recorre las bbdd encontradas y las añade al combobox
                for (int i = 0; i < conexion.getNombreCatalogos().size(); i++) 
                {
                    cadena = (String) conexion.getNombreCatalogos().get(i);
                    cmbBbdd.addItem( cadena );
                }
                // a partir de aqui el acceso sera a bbdd seleccionada
                acceso=true;
                lblDisponibles.setVisible(true);
                lblNombreBbdd.setVisible(true);
                txtBaseDatos.setVisible(true);
                cmbBbdd.setVisible(true);
            }    
            else 
            {
                System.out.println("faltan datos");
            }
        } 
        else if (txtBaseDatos.getText() != null && txtUsuario.getText() != null 
                && txtContraseña.getPassword() != null) 
        {
            // establezco una conexion con los valores introducidos
            conexion = new ConexionMySql( txtBaseDatos.getText(), 
                    txtUsuario.getText() , 
                    String.valueOf( txtContraseña.getPassword() ) );
            
            this.setVisible(false);
            
            // desconecto la conexion porque tengo guardados los valores en el formulario
            conexion.getDesconexion();
            
        } else {
            System.out.println("faltan datos");
        }
        
    }//GEN-LAST:event_btnAccesoActionPerformed

    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseEntered
        // TODO add your handling code here:
        //txtContraseña.setText("");
    }//GEN-LAST:event_txtContraseñaMouseEntered

    private void jLabelIconoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoMousePressed
        // TODO add your handling code here:
        txtBaseDatos.setText("mibasedatos");
        txtUsuario.setText("root");
        txtContraseña.setText("12345.Aaa");
    }//GEN-LAST:event_jLabelIconoMousePressed

    private void cmbBbddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBbddItemStateChanged
        // TODO add your handling code here:
        txtBaseDatos.setText( String.valueOf( cmbBbdd.getSelectedItem() ) );
    }//GEN-LAST:event_cmbBbddItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoBbdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoBbdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoBbdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoBbdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccesoBbdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbBbdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JLabel lblNombreBbdd;
    public static javax.swing.JTextField txtBaseDatos;
    public static javax.swing.JPasswordField txtContraseña;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
