/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Conexion.ClassCampos;
import Conexion.ConexionMySql;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author javier
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() throws SQLException {
        initComponents();
        
        // centrar el formulario en la ventan
        this.setLocationRelativeTo(null);
        
        ponerCampos();
    }
    
    public void ponerCampos() throws SQLException
    {
        ClassCampos classCampos = new ClassCampos();
        ArrayList <ClassCampos> arrayCamposConexion = AccesoBbdd.conexion2.getaCCampos();
        ResultSet datos = Principal.listaDatos;
        
        int numeroRegistros = 0;

        // calcula el numero de registros devueltos por la consulta
        try 
        {
            datos.last(); // va al ultimo registro
            numeroRegistros = datos.getRow();
            datos.beforeFirst(); // vuelve al primero
        } 
        catch (SQLException ex) 
        {
            System.out.println("Error en el conteo. \n" +ex.getMessage());
        }
            
        int fila = Principal.filaDatos;
        System.out.println("la fila "+ fila + " registros  "+ numeroRegistros);
        //<editor-fold defaultstate="collapsed" desc="Cabezera de la tabla">
        
        JLabel etiqueta0 = new JLabel();
        etiqueta0.setText( "CAMPO" );
        etiqueta0.setFont(new java.awt.Font("Lucida Grande", 1, 14));

        JLabel etiqueta1 = new JLabel();
        etiqueta1.setText("TIPO" );
        etiqueta1.setFont(new java.awt.Font("Lucida Grande", 1, 14));

        JLabel etiqueta2 = new JLabel();
        etiqueta2.setText("VALOR" );
        etiqueta2.setFont(new java.awt.Font("Lucida Grande", 1, 14));

        jPanel1.add(etiqueta0);
        jPanel1.add(etiqueta1);
        jPanel1.add(etiqueta2);
        //</editor-fold>
        
        for (int i = 0; i < arrayCamposConexion.size(); i++) 
        {
            classCampos = arrayCamposConexion.get(i);
            JLabel etiqueta3 = new JLabel();
            etiqueta3.setText( classCampos.getNombreCampo() );
            etiqueta3.setFont(new java.awt.Font("Lucida Grande", 1, 16));
            //etiqueta2.setForeground(new java.awt.Color(255, 255, 255));
            //etiqueta.setBackground(new java.awt.Color(0, 0, 153));

            JLabel etiqueta4 = new JLabel();
            etiqueta4.setText("(" + classCampos.getTipoCampo() +")" );
            etiqueta4.setFont(new java.awt.Font("Lucida Grande", 1, 12));
            //etiqueta2.setForeground(new java.awt.Color(255, 255, 255));
            
            JTextArea texto1 = new JTextArea();
            String valor = "";
            int x = 0;
            while (datos.next())
            {
                System.out.println("-- fila "+x);
                if (x==fila) 
                {
                    valor = String.valueOf( datos.getString(i+1) ) ;
                }
                x++;
            }
            datos.beforeFirst(); // vuelve al primero
            texto1.setText( valor );
            texto1.setFont(new java.awt.Font("Lucida Grande", 1, 14));
            //texto.setForeground(new java.awt.Color(255, 255, 255));
            
            jPanel1.add(etiqueta3);
            jPanel1.add(etiqueta4);
            jPanel1.add(texto1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel1.setText("MODIFICACION DE DATOS ");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setText("PARA GUARDAR : MENU CAMBIOS - GUARDAR");

        jMenu1.setText("Cambios");

        jMenuItem2.setText("Cancelar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Modificar().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
